### ISSUE TITLE
Couldnt find my lightstrip

### ISSUE THREAD

**Issue by 18605000242** [Yeelight/Yeelight-Chroma-Connector#2]
I turned on the LAN CONTROL on the yeelight app but couldn't find it on the Yeelight Chroma Connector.
My lightstrip model is yeelink.light.strip2
Anyone has any solution?

**Comment by yyccz123** [comment]
1.Ensure that the PC and the lightstrip are in the same IP network segment,such as 192.168.1.xxx
2.Ensure that the lightstrip's firmware ver is 2.1.7_0019
3.Ensure that Yeelight Chroma Connector ver is 1.0.13
4.If all the preceding conditions are met, restart the lightstrip or the PC

**Comment by 18605000242** [comment]
Thank you for your replying.
However, my device's firmware is 2.0.6_0073 and couldn't find any newer ver via both Yeelight or Xiaomi app.
Light strip model is yeelink.light.strip2, does it mean it can't support Razer Chroma?

**Comment by yyccz123** [comment]
yeelink.light.strip2 does not support Razer Chroma，you can buy yeelink.light.stripa instead

**Comment by 18605000242** [comment]
hahaha, sure, already placed an order during Double 12. Many thanks!
